name: Hello World

on: 
  workflow_dispatch:

env:
  BASE_BRANCH_NAME: main
  HOSTING_BRANCH_NAME: gh-pages
  LOCAL_BRANCH_NAME: gh-pages-local

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
    - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd $GITHUB_WORKSPACE
          git fetch          
      - name: Clean up
        # The reason why we don't use origin/gh-pages and just merge to it is, to prevent git complains gh-pages and the base branch have unrelated histories and conflicts on merge (it should never happen. idk why this happens)
        continue-on-error: true
        run: |
          git branch -d $LOCAL_BRANCH_NAME
      - name: Checkout
        run: |
          git fetch
          git checkout $BASE_BRANCH_NAME
          git pull
          git checkout -b $LOCAL_BRANCH_NAME
      - name: Commit
        run: |
          git add .
          git commit -m 'Generated automatically'
          git push -f origin $LOCAL_BRANCH_NAME:$HOSTING_BRANCH_NAME
      - name: Teardown when the workflow failed
        if: failure() && steps.build_step.outcome == 'failure'
        run: |
          git stash -u